name: CI

on: [push, pull_request]

jobs:
  test-and-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test
      - name: Build
        run: pnpm run build
